<?php

declare(strict_types=1);

namespace App\Components\YearForm;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface YearFormFactory
{
	public function create(): YearForm;
}
