<?php

declare(strict_types=1);

namespace App\Components\TeamMessage;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface TeamMessageFactory
{
	public function create(): TeamMessage;
}
