<?php

declare(strict_types=1);

namespace App\Components\CardScreen;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface CardScreenFactory
{
	public function create(): CardScreen;
}
