<?php

declare(strict_types=1);

namespace App\Components\CheckpointCard;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface CheckpointCardFactory
{
	public function create(): CheckpointCard;
}
