<?php

declare(strict_types=1);

namespace App\Components\TeamCard;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface TeamCardFactory
{
	public function create(): TeamCard;
}
