<?php

declare(strict_types=1);

namespace App\Components\UpdatesForm;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface UpdatesFormFactory
{
	public function create(): UpdatesForm;
}
