<?php

declare(strict_types=1);

namespace App\Components\CheckpointScreen;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface CheckpointScreenFactory
{
	public function create(): CheckpointScreen;
}
