<?php

declare(strict_types=1);

namespace App\Components\InfoScreen;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface InfoScreenFactory
{
	public function create(): InfoScreen;
}
