<?php

declare(strict_types=1);

namespace App\Components\ActionScreen;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface ActionScreenFactory
{
	public function create(): ActionScreen;
}
