<?php

declare(strict_types=1);

namespace App\Components\DiscussionControl;


/**
 * Generated by Nette DI (registered in services.neon).
 */
interface DiscussionControlFactory
{
	public function create(): DiscussionControl;
}
